
export const REST_ADAPTER = 'REST_ADAPTER';
export const PERSISTENCY_ADAPTER = 'PERSISTENCY_ADAPTER';
export const CONFIRM_USECASE = 'CONFIRM_USECASE';
export const REFUND_USECASE = 'REFUND_USECASE';